#!/bin/bash
rmdir --ignore-fail-on-non-empty /home/jovyan/work

workdir='/home/jovyan/drive'
mkdir -p ${workdir}

cd /workspace
if [ ! -L drive ]; then
  ln -s /home/jovyan/drive/
fi

server="http://${NEXTCLOUD_HOST:-localhost:8081}"
json_file="${workdir}/.access_token.json"

function refresh_token {
  json="$(curl --header "Authorization: token ${JUPYTERHUB_API_TOKEN}" http://${JUPYTER_HOST}/services/refresh-token/tokens)"
  if [[ -z "${json}" ]]; then
    token="${NEXTCLOUD_ACCESS_TOKEN}"
    json="{ \"access_token\": \"${token}\", \"token_expires\": $(date -d "10 min" +%s).0000000 }"
  fi
  echo "${json}" > "${json_file}"
  token=$(jq -r '.access_token' "${json_file}")
  echo "${token}"
}

function get_token {
  if [[ -f "${json_file}" ]]; then
    now=$(date +%s)
    token=$(jq -r '.access_token' "${json_file}")
    expires_at=$(jq -r '.token_expires' "${json_file}"| sed 's/\..*//')
    if [[ "${expires_at}" -lt ${now} ]]; then
      token=$(refresh_token)
    fi
  else
    token=$(refresh_token)
  fi
  echo "${token}"
}

function ncsync {
  while true; do
    token="$(get_token)"

    if [[ -n "${token}" && "${token}" != "null" && -n "${JUPYTERHUB_USER}" ]]; then
      nextcloudcmd -n -s \
        --user "${JUPYTERHUB_USER}" \
        --password "${token}" \
        --path / \
        "${workdir}" \
        "${server}" || true
    else
      echo "[nc-sync] missing token or user, skipping sync"
    fi

    sleep 5s
  done
}

ncsync &