name: Build and publish Docker image
on:
  push:
    branches: [ main, master, develop ]
    tags:
      - "*"
  pull_request:
    branches: [ main, master, develop ]
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: ./
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eoepca/pde-code-server
          tag_with_ref: true
